version: '3.9'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    environment:
      - FLASK_APP=backend.app
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:password@db:5432/postgres
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - .:/app
    command: flask run --host=0.0.0.0 --reload

  web:
    image: nginx:alpine
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    ports:
      - "80:80"
    depends_on:
      - app
      
volumes:
  pgdata: